# Generated by Django 5.0.3 on 2024-03-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0004_alter_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(blank=True, choices=[('stationary', 'stationary'), ('cables', 'cables'), ('electronics', 'electronics'), ('tablets', 'tablets'), ('capsules', 'capsules'), ('injectables', 'injectables'), ('solutions', 'solutions'), ('sachets', 'sachets')], max_length=50, null=True),
        ),
    ]
